// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gzone_data.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GlobalConfigModifyFlag int32

const (
	GlobalConfigModifyFlag_GCMF_DEFAULT       GlobalConfigModifyFlag = 0
	GlobalConfigModifyFlag_GCMF_COMMENT_LIMIT GlobalConfigModifyFlag = 1
	GlobalConfigModifyFlag_GCMF_MOMEMT_LIMIT  GlobalConfigModifyFlag = 2
)

var GlobalConfigModifyFlag_name = map[int32]string{
	0: "GCMF_DEFAULT",
	1: "GCMF_COMMENT_LIMIT",
	2: "GCMF_MOMEMT_LIMIT",
}

var GlobalConfigModifyFlag_value = map[string]int32{
	"GCMF_DEFAULT":       0,
	"GCMF_COMMENT_LIMIT": 1,
	"GCMF_MOMEMT_LIMIT":  2,
}

func (x GlobalConfigModifyFlag) String() string {
	return proto.EnumName(GlobalConfigModifyFlag_name, int32(x))
}

func (GlobalConfigModifyFlag) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_92f92e011548d12d, []int{0}
}

type ZoneConfigModifyFlag int32

const (
	ZoneConfigModifyFlag_ZCMF_DEFAULT       ZoneConfigModifyFlag = 0
	ZoneConfigModifyFlag_ZCMF_COMMENT_LIMIT ZoneConfigModifyFlag = 1
	ZoneConfigModifyFlag_ZCMF_MESSAGE_LIMIT ZoneConfigModifyFlag = 2
	ZoneConfigModifyFlag_ZCMF_REMIND        ZoneConfigModifyFlag = 4
)

var ZoneConfigModifyFlag_name = map[int32]string{
	0: "ZCMF_DEFAULT",
	1: "ZCMF_COMMENT_LIMIT",
	2: "ZCMF_MESSAGE_LIMIT",
	4: "ZCMF_REMIND",
}

var ZoneConfigModifyFlag_value = map[string]int32{
	"ZCMF_DEFAULT":       0,
	"ZCMF_COMMENT_LIMIT": 1,
	"ZCMF_MESSAGE_LIMIT": 2,
	"ZCMF_REMIND":        4,
}

func (x ZoneConfigModifyFlag) String() string {
	return proto.EnumName(ZoneConfigModifyFlag_name, int32(x))
}

func (ZoneConfigModifyFlag) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_92f92e011548d12d, []int{1}
}

type GameProfileModifyFlag int32

const (
	GameProfileModifyFlag_GPMF_DEFAULT      GameProfileModifyFlag = 0
	GameProfileModifyFlag_GPMF_OPEN_ID      GameProfileModifyFlag = 1
	GameProfileModifyFlag_GPMF_ROLE_NAME    GameProfileModifyFlag = 2
	GameProfileModifyFlag_GPMF_WORLD_ID     GameProfileModifyFlag = 4
	GameProfileModifyFlag_GPMF_LEVEL        GameProfileModifyFlag = 8
	GameProfileModifyFlag_GPMF_GAME_PROFILE GameProfileModifyFlag = 16
)

var GameProfileModifyFlag_name = map[int32]string{
	0:  "GPMF_DEFAULT",
	1:  "GPMF_OPEN_ID",
	2:  "GPMF_ROLE_NAME",
	4:  "GPMF_WORLD_ID",
	8:  "GPMF_LEVEL",
	16: "GPMF_GAME_PROFILE",
}

var GameProfileModifyFlag_value = map[string]int32{
	"GPMF_DEFAULT":      0,
	"GPMF_OPEN_ID":      1,
	"GPMF_ROLE_NAME":    2,
	"GPMF_WORLD_ID":     4,
	"GPMF_LEVEL":        8,
	"GPMF_GAME_PROFILE": 16,
}

func (x GameProfileModifyFlag) String() string {
	return proto.EnumName(GameProfileModifyFlag_name, int32(x))
}

func (GameProfileModifyFlag) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_92f92e011548d12d, []int{2}
}

type ZoneProfileModifyFlag int32

const (
	ZoneProfileModifyFlag_ZPMF_DEAFULT    ZoneProfileModifyFlag = 0
	ZoneProfileModifyFlag_ZPMF_HEAD_FRAME ZoneProfileModifyFlag = 1
	ZoneProfileModifyFlag_ZPMF_SIGNATURE  ZoneProfileModifyFlag = 2
	ZoneProfileModifyFlag_ZPMF_LOCATION   ZoneProfileModifyFlag = 4
)

var ZoneProfileModifyFlag_name = map[int32]string{
	0: "ZPMF_DEAFULT",
	1: "ZPMF_HEAD_FRAME",
	2: "ZPMF_SIGNATURE",
	4: "ZPMF_LOCATION",
}

var ZoneProfileModifyFlag_value = map[string]int32{
	"ZPMF_DEAFULT":    0,
	"ZPMF_HEAD_FRAME": 1,
	"ZPMF_SIGNATURE":  2,
	"ZPMF_LOCATION":   4,
}

func (x ZoneProfileModifyFlag) String() string {
	return proto.EnumName(ZoneProfileModifyFlag_name, int32(x))
}

func (ZoneProfileModifyFlag) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_92f92e011548d12d, []int{3}
}

type TopicModifyFlag int32

const (
	TopicModifyFlag_TMF_DEFAULT    TopicModifyFlag = 0
	TopicModifyFlag_TMF_TITLE      TopicModifyFlag = 1
	TopicModifyFlag_TMF_CONTENT    TopicModifyFlag = 2
	TopicModifyFlag_TMF_START_TIME TopicModifyFlag = 4
	TopicModifyFlag_TMF_END_TIME   TopicModifyFlag = 8
)

var TopicModifyFlag_name = map[int32]string{
	0: "TMF_DEFAULT",
	1: "TMF_TITLE",
	2: "TMF_CONTENT",
	4: "TMF_START_TIME",
	8: "TMF_END_TIME",
}

var TopicModifyFlag_value = map[string]int32{
	"TMF_DEFAULT":    0,
	"TMF_TITLE":      1,
	"TMF_CONTENT":    2,
	"TMF_START_TIME": 4,
	"TMF_END_TIME":   8,
}

func (x TopicModifyFlag) String() string {
	return proto.EnumName(TopicModifyFlag_name, int32(x))
}

func (TopicModifyFlag) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_92f92e011548d12d, []int{4}
}

//全局空间设置
type GlobalZoneConfig struct {
	BMomentLimit         int32    `protobuf:"varint,1,opt,name=BMomentLimit,proto3" json:"BMomentLimit,omitempty"`
	BCommentLimit        int32    `protobuf:"varint,2,opt,name=BCommentLimit,proto3" json:"BCommentLimit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GlobalZoneConfig) Reset()         { *m = GlobalZoneConfig{} }
func (m *GlobalZoneConfig) String() string { return proto.CompactTextString(m) }
func (*GlobalZoneConfig) ProtoMessage()    {}
func (*GlobalZoneConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_92f92e011548d12d, []int{0}
}

func (m *GlobalZoneConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GlobalZoneConfig.Unmarshal(m, b)
}
func (m *GlobalZoneConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GlobalZoneConfig.Marshal(b, m, deterministic)
}
func (m *GlobalZoneConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GlobalZoneConfig.Merge(m, src)
}
func (m *GlobalZoneConfig) XXX_Size() int {
	return xxx_messageInfo_GlobalZoneConfig.Size(m)
}
func (m *GlobalZoneConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_GlobalZoneConfig.DiscardUnknown(m)
}

var xxx_messageInfo_GlobalZoneConfig proto.InternalMessageInfo

func (m *GlobalZoneConfig) GetBMomentLimit() int32 {
	if m != nil {
		return m.BMomentLimit
	}
	return 0
}

func (m *GlobalZoneConfig) GetBCommentLimit() int32 {
	if m != nil {
		return m.BCommentLimit
	}
	return 0
}

//空间设置
type ZoneConfig struct {
	DwCommentLimit       uint32   `protobuf:"varint,1,opt,name=DwCommentLimit,proto3" json:"DwCommentLimit,omitempty"`
	DwMessageLimit       uint32   `protobuf:"varint,2,opt,name=DwMessageLimit,proto3" json:"DwMessageLimit,omitempty"`
	DwRemind             uint32   `protobuf:"varint,3,opt,name=DwRemind,proto3" json:"DwRemind,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ZoneConfig) Reset()         { *m = ZoneConfig{} }
func (m *ZoneConfig) String() string { return proto.CompactTextString(m) }
func (*ZoneConfig) ProtoMessage()    {}
func (*ZoneConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_92f92e011548d12d, []int{1}
}

func (m *ZoneConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZoneConfig.Unmarshal(m, b)
}
func (m *ZoneConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZoneConfig.Marshal(b, m, deterministic)
}
func (m *ZoneConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZoneConfig.Merge(m, src)
}
func (m *ZoneConfig) XXX_Size() int {
	return xxx_messageInfo_ZoneConfig.Size(m)
}
func (m *ZoneConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ZoneConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ZoneConfig proto.InternalMessageInfo

func (m *ZoneConfig) GetDwCommentLimit() uint32 {
	if m != nil {
		return m.DwCommentLimit
	}
	return 0
}

func (m *ZoneConfig) GetDwMessageLimit() uint32 {
	if m != nil {
		return m.DwMessageLimit
	}
	return 0
}

func (m *ZoneConfig) GetDwRemind() uint32 {
	if m != nil {
		return m.DwRemind
	}
	return 0
}

//游戏侧的玩家数据
type GameUserProfile struct {
	SzOpenID             string   `protobuf:"bytes,1,opt,name=SzOpenID,proto3" json:"SzOpenID,omitempty"`
	SzRoleName           string   `protobuf:"bytes,2,opt,name=SzRoleName,proto3" json:"SzRoleName,omitempty"`
	DwWorldID            uint32   `protobuf:"varint,3,opt,name=DwWorldID,proto3" json:"DwWorldID,omitempty"`
	DwLevel              uint32   `protobuf:"varint,4,opt,name=DwLevel,proto3" json:"DwLevel,omitempty"`
	UserGameProfile      string   `protobuf:"bytes,5,opt,name=UserGameProfile,proto3" json:"UserGameProfile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameUserProfile) Reset()         { *m = GameUserProfile{} }
func (m *GameUserProfile) String() string { return proto.CompactTextString(m) }
func (*GameUserProfile) ProtoMessage()    {}
func (*GameUserProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_92f92e011548d12d, []int{2}
}

func (m *GameUserProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameUserProfile.Unmarshal(m, b)
}
func (m *GameUserProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameUserProfile.Marshal(b, m, deterministic)
}
func (m *GameUserProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameUserProfile.Merge(m, src)
}
func (m *GameUserProfile) XXX_Size() int {
	return xxx_messageInfo_GameUserProfile.Size(m)
}
func (m *GameUserProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_GameUserProfile.DiscardUnknown(m)
}

var xxx_messageInfo_GameUserProfile proto.InternalMessageInfo

func (m *GameUserProfile) GetSzOpenID() string {
	if m != nil {
		return m.SzOpenID
	}
	return ""
}

func (m *GameUserProfile) GetSzRoleName() string {
	if m != nil {
		return m.SzRoleName
	}
	return ""
}

func (m *GameUserProfile) GetDwWorldID() uint32 {
	if m != nil {
		return m.DwWorldID
	}
	return 0
}

func (m *GameUserProfile) GetDwLevel() uint32 {
	if m != nil {
		return m.DwLevel
	}
	return 0
}

func (m *GameUserProfile) GetUserGameProfile() string {
	if m != nil {
		return m.UserGameProfile
	}
	return ""
}

//空间侧的玩家数据
type ZoneUserProfile struct {
	SzHeadFrame          string   `protobuf:"bytes,1,opt,name=SzHeadFrame,proto3" json:"SzHeadFrame,omitempty"`
	SzSignature          string   `protobuf:"bytes,2,opt,name=SzSignature,proto3" json:"SzSignature,omitempty"`
	SzLocation           string   `protobuf:"bytes,3,opt,name=SzLocation,proto3" json:"SzLocation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ZoneUserProfile) Reset()         { *m = ZoneUserProfile{} }
func (m *ZoneUserProfile) String() string { return proto.CompactTextString(m) }
func (*ZoneUserProfile) ProtoMessage()    {}
func (*ZoneUserProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_92f92e011548d12d, []int{3}
}

func (m *ZoneUserProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZoneUserProfile.Unmarshal(m, b)
}
func (m *ZoneUserProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZoneUserProfile.Marshal(b, m, deterministic)
}
func (m *ZoneUserProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZoneUserProfile.Merge(m, src)
}
func (m *ZoneUserProfile) XXX_Size() int {
	return xxx_messageInfo_ZoneUserProfile.Size(m)
}
func (m *ZoneUserProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_ZoneUserProfile.DiscardUnknown(m)
}

var xxx_messageInfo_ZoneUserProfile proto.InternalMessageInfo

func (m *ZoneUserProfile) GetSzHeadFrame() string {
	if m != nil {
		return m.SzHeadFrame
	}
	return ""
}

func (m *ZoneUserProfile) GetSzSignature() string {
	if m != nil {
		return m.SzSignature
	}
	return ""
}

func (m *ZoneUserProfile) GetSzLocation() string {
	if m != nil {
		return m.SzLocation
	}
	return ""
}

//空间个人数据
type ZoneProfileSet struct {
	UllRoleID     uint64           `protobuf:"varint,1,opt,name=UllRoleID,proto3" json:"UllRoleID,omitempty"`
	StZoneProfile *ZoneUserProfile `protobuf:"bytes,2,opt,name=StZoneProfile,proto3" json:"StZoneProfile,omitempty"`
	StGameProFile *GameUserProfile `protobuf:"bytes,3,opt,name=StGameProFile,proto3" json:"StGameProFile,omitempty"`
	StZoneConfig  *ZoneConfig      `protobuf:"bytes,4,opt,name=StZoneConfig,proto3" json:"StZoneConfig,omitempty"`
	//统计相关
	DwVisitorCount       uint32   `protobuf:"varint,5,opt,name=DwVisitorCount,proto3" json:"DwVisitorCount,omitempty"`
	DwCommentCount       uint32   `protobuf:"varint,6,opt,name=DwCommentCount,proto3" json:"DwCommentCount,omitempty"`
	DwLikeCount          uint32   `protobuf:"varint,7,opt,name=DwLikeCount,proto3" json:"DwLikeCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ZoneProfileSet) Reset()         { *m = ZoneProfileSet{} }
func (m *ZoneProfileSet) String() string { return proto.CompactTextString(m) }
func (*ZoneProfileSet) ProtoMessage()    {}
func (*ZoneProfileSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_92f92e011548d12d, []int{4}
}

func (m *ZoneProfileSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZoneProfileSet.Unmarshal(m, b)
}
func (m *ZoneProfileSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZoneProfileSet.Marshal(b, m, deterministic)
}
func (m *ZoneProfileSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZoneProfileSet.Merge(m, src)
}
func (m *ZoneProfileSet) XXX_Size() int {
	return xxx_messageInfo_ZoneProfileSet.Size(m)
}
func (m *ZoneProfileSet) XXX_DiscardUnknown() {
	xxx_messageInfo_ZoneProfileSet.DiscardUnknown(m)
}

var xxx_messageInfo_ZoneProfileSet proto.InternalMessageInfo

func (m *ZoneProfileSet) GetUllRoleID() uint64 {
	if m != nil {
		return m.UllRoleID
	}
	return 0
}

func (m *ZoneProfileSet) GetStZoneProfile() *ZoneUserProfile {
	if m != nil {
		return m.StZoneProfile
	}
	return nil
}

func (m *ZoneProfileSet) GetStGameProFile() *GameUserProfile {
	if m != nil {
		return m.StGameProFile
	}
	return nil
}

func (m *ZoneProfileSet) GetStZoneConfig() *ZoneConfig {
	if m != nil {
		return m.StZoneConfig
	}
	return nil
}

func (m *ZoneProfileSet) GetDwVisitorCount() uint32 {
	if m != nil {
		return m.DwVisitorCount
	}
	return 0
}

func (m *ZoneProfileSet) GetDwCommentCount() uint32 {
	if m != nil {
		return m.DwCommentCount
	}
	return 0
}

func (m *ZoneProfileSet) GetDwLikeCount() uint32 {
	if m != nil {
		return m.DwLikeCount
	}
	return 0
}

//心情
type Moment struct {
	UllMomentID          uint64         `protobuf:"varint,1,opt,name=UllMomentID,proto3" json:"UllMomentID,omitempty"`
	UllRoleID            uint64         `protobuf:"varint,2,opt,name=UllRoleID,proto3" json:"UllRoleID,omitempty"`
	SzRoleName           string         `protobuf:"bytes,3,opt,name=SzRoleName,proto3" json:"SzRoleName,omitempty"`
	UllWorldID           uint64         `protobuf:"varint,4,opt,name=UllWorldID,proto3" json:"UllWorldID,omitempty"`
	UllTopicID           uint64         `protobuf:"varint,5,opt,name=UllTopicID,proto3" json:"UllTopicID,omitempty"`
	BIsHot               uint32         `protobuf:"varint,6,opt,name=BIsHot,proto3" json:"BIsHot,omitempty"`
	DwTime               int64          `protobuf:"varint,7,opt,name=DwTime,proto3" json:"DwTime,omitempty"`
	SzContent            string         `protobuf:"bytes,8,opt,name=SzContent,proto3" json:"SzContent,omitempty"`
	SzLocation           string         `protobuf:"bytes,9,opt,name=SzLocation,proto3" json:"SzLocation,omitempty"`
	BNum                 uint32         `protobuf:"varint,10,opt,name=BNum,proto3" json:"BNum,omitempty"`
	AstMediaData         *MediaUnitList `protobuf:"bytes,11,opt,name=AstMediaData,proto3" json:"AstMediaData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Moment) Reset()         { *m = Moment{} }
func (m *Moment) String() string { return proto.CompactTextString(m) }
func (*Moment) ProtoMessage()    {}
func (*Moment) Descriptor() ([]byte, []int) {
	return fileDescriptor_92f92e011548d12d, []int{5}
}

func (m *Moment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Moment.Unmarshal(m, b)
}
func (m *Moment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Moment.Marshal(b, m, deterministic)
}
func (m *Moment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Moment.Merge(m, src)
}
func (m *Moment) XXX_Size() int {
	return xxx_messageInfo_Moment.Size(m)
}
func (m *Moment) XXX_DiscardUnknown() {
	xxx_messageInfo_Moment.DiscardUnknown(m)
}

var xxx_messageInfo_Moment proto.InternalMessageInfo

func (m *Moment) GetUllMomentID() uint64 {
	if m != nil {
		return m.UllMomentID
	}
	return 0
}

func (m *Moment) GetUllRoleID() uint64 {
	if m != nil {
		return m.UllRoleID
	}
	return 0
}

func (m *Moment) GetSzRoleName() string {
	if m != nil {
		return m.SzRoleName
	}
	return ""
}

func (m *Moment) GetUllWorldID() uint64 {
	if m != nil {
		return m.UllWorldID
	}
	return 0
}

func (m *Moment) GetUllTopicID() uint64 {
	if m != nil {
		return m.UllTopicID
	}
	return 0
}

func (m *Moment) GetBIsHot() uint32 {
	if m != nil {
		return m.BIsHot
	}
	return 0
}

func (m *Moment) GetDwTime() int64 {
	if m != nil {
		return m.DwTime
	}
	return 0
}

func (m *Moment) GetSzContent() string {
	if m != nil {
		return m.SzContent
	}
	return ""
}

func (m *Moment) GetSzLocation() string {
	if m != nil {
		return m.SzLocation
	}
	return ""
}

func (m *Moment) GetBNum() uint32 {
	if m != nil {
		return m.BNum
	}
	return 0
}

func (m *Moment) GetAstMediaData() *MediaUnitList {
	if m != nil {
		return m.AstMediaData
	}
	return nil
}

//多媒体单元
type MediaUnitList struct {
	AstMediaList         []*MediaUnitList_MediaUnit `protobuf:"bytes,1,rep,name=AstMediaList,proto3" json:"AstMediaList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *MediaUnitList) Reset()         { *m = MediaUnitList{} }
func (m *MediaUnitList) String() string { return proto.CompactTextString(m) }
func (*MediaUnitList) ProtoMessage()    {}
func (*MediaUnitList) Descriptor() ([]byte, []int) {
	return fileDescriptor_92f92e011548d12d, []int{6}
}

func (m *MediaUnitList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MediaUnitList.Unmarshal(m, b)
}
func (m *MediaUnitList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MediaUnitList.Marshal(b, m, deterministic)
}
func (m *MediaUnitList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MediaUnitList.Merge(m, src)
}
func (m *MediaUnitList) XXX_Size() int {
	return xxx_messageInfo_MediaUnitList.Size(m)
}
func (m *MediaUnitList) XXX_DiscardUnknown() {
	xxx_messageInfo_MediaUnitList.DiscardUnknown(m)
}

var xxx_messageInfo_MediaUnitList proto.InternalMessageInfo

func (m *MediaUnitList) GetAstMediaList() []*MediaUnitList_MediaUnit {
	if m != nil {
		return m.AstMediaList
	}
	return nil
}

type MediaUnitList_MediaUnit struct {
	Bmessage             uint32   `protobuf:"varint,1,opt,name=Bmessage,proto3" json:"Bmessage,omitempty"`
	SzParam1             string   `protobuf:"bytes,2,opt,name=SzParam1,proto3" json:"SzParam1,omitempty"`
	SzParam2             string   `protobuf:"bytes,3,opt,name=SzParam2,proto3" json:"SzParam2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MediaUnitList_MediaUnit) Reset()         { *m = MediaUnitList_MediaUnit{} }
func (m *MediaUnitList_MediaUnit) String() string { return proto.CompactTextString(m) }
func (*MediaUnitList_MediaUnit) ProtoMessage()    {}
func (*MediaUnitList_MediaUnit) Descriptor() ([]byte, []int) {
	return fileDescriptor_92f92e011548d12d, []int{6, 0}
}

func (m *MediaUnitList_MediaUnit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MediaUnitList_MediaUnit.Unmarshal(m, b)
}
func (m *MediaUnitList_MediaUnit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MediaUnitList_MediaUnit.Marshal(b, m, deterministic)
}
func (m *MediaUnitList_MediaUnit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MediaUnitList_MediaUnit.Merge(m, src)
}
func (m *MediaUnitList_MediaUnit) XXX_Size() int {
	return xxx_messageInfo_MediaUnitList_MediaUnit.Size(m)
}
func (m *MediaUnitList_MediaUnit) XXX_DiscardUnknown() {
	xxx_messageInfo_MediaUnitList_MediaUnit.DiscardUnknown(m)
}

var xxx_messageInfo_MediaUnitList_MediaUnit proto.InternalMessageInfo

func (m *MediaUnitList_MediaUnit) GetBmessage() uint32 {
	if m != nil {
		return m.Bmessage
	}
	return 0
}

func (m *MediaUnitList_MediaUnit) GetSzParam1() string {
	if m != nil {
		return m.SzParam1
	}
	return ""
}

func (m *MediaUnitList_MediaUnit) GetSzParam2() string {
	if m != nil {
		return m.SzParam2
	}
	return ""
}

//心情数据集合
type MomentDataSet struct {
	StMoment             *Moment    `protobuf:"bytes,1,opt,name=StMoment,proto3" json:"StMoment,omitempty"`
	DwTotalLikeNum       uint32     `protobuf:"varint,2,opt,name=DwTotalLikeNum,proto3" json:"DwTotalLikeNum,omitempty"`
	AstLike              []*DoLike  `protobuf:"bytes,3,rep,name=AstLike,proto3" json:"AstLike,omitempty"`
	DwTotalCommentNum    uint32     `protobuf:"varint,4,opt,name=DwTotalCommentNum,proto3" json:"DwTotalCommentNum,omitempty"`
	AstComment           []*Comment `protobuf:"bytes,5,rep,name=AstComment,proto3" json:"AstComment,omitempty"`
	BIsLike              bool       `protobuf:"varint,6,opt,name=BIsLike,proto3" json:"BIsLike,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *MomentDataSet) Reset()         { *m = MomentDataSet{} }
func (m *MomentDataSet) String() string { return proto.CompactTextString(m) }
func (*MomentDataSet) ProtoMessage()    {}
func (*MomentDataSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_92f92e011548d12d, []int{7}
}

func (m *MomentDataSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MomentDataSet.Unmarshal(m, b)
}
func (m *MomentDataSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MomentDataSet.Marshal(b, m, deterministic)
}
func (m *MomentDataSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MomentDataSet.Merge(m, src)
}
func (m *MomentDataSet) XXX_Size() int {
	return xxx_messageInfo_MomentDataSet.Size(m)
}
func (m *MomentDataSet) XXX_DiscardUnknown() {
	xxx_messageInfo_MomentDataSet.DiscardUnknown(m)
}

var xxx_messageInfo_MomentDataSet proto.InternalMessageInfo

func (m *MomentDataSet) GetStMoment() *Moment {
	if m != nil {
		return m.StMoment
	}
	return nil
}

func (m *MomentDataSet) GetDwTotalLikeNum() uint32 {
	if m != nil {
		return m.DwTotalLikeNum
	}
	return 0
}

func (m *MomentDataSet) GetAstLike() []*DoLike {
	if m != nil {
		return m.AstLike
	}
	return nil
}

func (m *MomentDataSet) GetDwTotalCommentNum() uint32 {
	if m != nil {
		return m.DwTotalCommentNum
	}
	return 0
}

func (m *MomentDataSet) GetAstComment() []*Comment {
	if m != nil {
		return m.AstComment
	}
	return nil
}

func (m *MomentDataSet) GetBIsLike() bool {
	if m != nil {
		return m.BIsLike
	}
	return false
}

//评论
type Comment struct {
	UllRoleID            uint64   `protobuf:"varint,1,opt,name=UllRoleID,proto3" json:"UllRoleID,omitempty"`
	SzRoleName           string   `protobuf:"bytes,2,opt,name=SzRoleName,proto3" json:"SzRoleName,omitempty"`
	UllCommentID         uint64   `protobuf:"varint,3,opt,name=UllCommentID,proto3" json:"UllCommentID,omitempty"`
	UllMomentID          uint64   `protobuf:"varint,4,opt,name=UllMomentID,proto3" json:"UllMomentID,omitempty"`
	DwTime               int64    `protobuf:"varint,5,opt,name=DwTime,proto3" json:"DwTime,omitempty"`
	SzContent            string   `protobuf:"bytes,6,opt,name=SzContent,proto3" json:"SzContent,omitempty"`
	UllReplyRoleId       uint64   `protobuf:"varint,7,opt,name=UllReplyRoleId,proto3" json:"UllReplyRoleId,omitempty"`
	SzReplyName          string   `protobuf:"bytes,8,opt,name=SzReplyName,proto3" json:"SzReplyName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Comment) Reset()         { *m = Comment{} }
func (m *Comment) String() string { return proto.CompactTextString(m) }
func (*Comment) ProtoMessage()    {}
func (*Comment) Descriptor() ([]byte, []int) {
	return fileDescriptor_92f92e011548d12d, []int{8}
}

func (m *Comment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Comment.Unmarshal(m, b)
}
func (m *Comment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Comment.Marshal(b, m, deterministic)
}
func (m *Comment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Comment.Merge(m, src)
}
func (m *Comment) XXX_Size() int {
	return xxx_messageInfo_Comment.Size(m)
}
func (m *Comment) XXX_DiscardUnknown() {
	xxx_messageInfo_Comment.DiscardUnknown(m)
}

var xxx_messageInfo_Comment proto.InternalMessageInfo

func (m *Comment) GetUllRoleID() uint64 {
	if m != nil {
		return m.UllRoleID
	}
	return 0
}

func (m *Comment) GetSzRoleName() string {
	if m != nil {
		return m.SzRoleName
	}
	return ""
}

func (m *Comment) GetUllCommentID() uint64 {
	if m != nil {
		return m.UllCommentID
	}
	return 0
}

func (m *Comment) GetUllMomentID() uint64 {
	if m != nil {
		return m.UllMomentID
	}
	return 0
}

func (m *Comment) GetDwTime() int64 {
	if m != nil {
		return m.DwTime
	}
	return 0
}

func (m *Comment) GetSzContent() string {
	if m != nil {
		return m.SzContent
	}
	return ""
}

func (m *Comment) GetUllReplyRoleId() uint64 {
	if m != nil {
		return m.UllReplyRoleId
	}
	return 0
}

func (m *Comment) GetSzReplyName() string {
	if m != nil {
		return m.SzReplyName
	}
	return ""
}

//点赞
type DoLike struct {
	UllRoleID            uint64   `protobuf:"varint,1,opt,name=UllRoleID,proto3" json:"UllRoleID,omitempty"`
	SzRoleName           string   `protobuf:"bytes,2,opt,name=SzRoleName,proto3" json:"SzRoleName,omitempty"`
	DwTime               int64    `protobuf:"varint,3,opt,name=DwTime,proto3" json:"DwTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DoLike) Reset()         { *m = DoLike{} }
func (m *DoLike) String() string { return proto.CompactTextString(m) }
func (*DoLike) ProtoMessage()    {}
func (*DoLike) Descriptor() ([]byte, []int) {
	return fileDescriptor_92f92e011548d12d, []int{9}
}

func (m *DoLike) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoLike.Unmarshal(m, b)
}
func (m *DoLike) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoLike.Marshal(b, m, deterministic)
}
func (m *DoLike) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoLike.Merge(m, src)
}
func (m *DoLike) XXX_Size() int {
	return xxx_messageInfo_DoLike.Size(m)
}
func (m *DoLike) XXX_DiscardUnknown() {
	xxx_messageInfo_DoLike.DiscardUnknown(m)
}

var xxx_messageInfo_DoLike proto.InternalMessageInfo

func (m *DoLike) GetUllRoleID() uint64 {
	if m != nil {
		return m.UllRoleID
	}
	return 0
}

func (m *DoLike) GetSzRoleName() string {
	if m != nil {
		return m.SzRoleName
	}
	return ""
}

func (m *DoLike) GetDwTime() int64 {
	if m != nil {
		return m.DwTime
	}
	return 0
}

//访客数据元
type Visitor struct {
	UllVisitorID         uint64   `protobuf:"varint,1,opt,name=UllVisitorID,proto3" json:"UllVisitorID,omitempty"`
	SzVisitorName        string   `protobuf:"bytes,2,opt,name=SzVisitorName,proto3" json:"SzVisitorName,omitempty"`
	DwTime               int64    `protobuf:"varint,3,opt,name=DwTime,proto3" json:"DwTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Visitor) Reset()         { *m = Visitor{} }
func (m *Visitor) String() string { return proto.CompactTextString(m) }
func (*Visitor) ProtoMessage()    {}
func (*Visitor) Descriptor() ([]byte, []int) {
	return fileDescriptor_92f92e011548d12d, []int{10}
}

func (m *Visitor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Visitor.Unmarshal(m, b)
}
func (m *Visitor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Visitor.Marshal(b, m, deterministic)
}
func (m *Visitor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Visitor.Merge(m, src)
}
func (m *Visitor) XXX_Size() int {
	return xxx_messageInfo_Visitor.Size(m)
}
func (m *Visitor) XXX_DiscardUnknown() {
	xxx_messageInfo_Visitor.DiscardUnknown(m)
}

var xxx_messageInfo_Visitor proto.InternalMessageInfo

func (m *Visitor) GetUllVisitorID() uint64 {
	if m != nil {
		return m.UllVisitorID
	}
	return 0
}

func (m *Visitor) GetSzVisitorName() string {
	if m != nil {
		return m.SzVisitorName
	}
	return ""
}

func (m *Visitor) GetDwTime() int64 {
	if m != nil {
		return m.DwTime
	}
	return 0
}

// 未处理的点赞或者评论消息
type UndealMsg struct {
	DwType               uint32   `protobuf:"varint,1,opt,name=DwType,proto3" json:"DwType,omitempty"`
	StLike               *DoLike  `protobuf:"bytes,2,opt,name=StLike,proto3" json:"StLike,omitempty"`
	StComment            *Comment `protobuf:"bytes,3,opt,name=StComment,proto3" json:"StComment,omitempty"`
	StMessage            *Comment `protobuf:"bytes,4,opt,name=StMessage,proto3" json:"StMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UndealMsg) Reset()         { *m = UndealMsg{} }
func (m *UndealMsg) String() string { return proto.CompactTextString(m) }
func (*UndealMsg) ProtoMessage()    {}
func (*UndealMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_92f92e011548d12d, []int{11}
}

func (m *UndealMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UndealMsg.Unmarshal(m, b)
}
func (m *UndealMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UndealMsg.Marshal(b, m, deterministic)
}
func (m *UndealMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UndealMsg.Merge(m, src)
}
func (m *UndealMsg) XXX_Size() int {
	return xxx_messageInfo_UndealMsg.Size(m)
}
func (m *UndealMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_UndealMsg.DiscardUnknown(m)
}

var xxx_messageInfo_UndealMsg proto.InternalMessageInfo

func (m *UndealMsg) GetDwType() uint32 {
	if m != nil {
		return m.DwType
	}
	return 0
}

func (m *UndealMsg) GetStLike() *DoLike {
	if m != nil {
		return m.StLike
	}
	return nil
}

func (m *UndealMsg) GetStComment() *Comment {
	if m != nil {
		return m.StComment
	}
	return nil
}

func (m *UndealMsg) GetStMessage() *Comment {
	if m != nil {
		return m.StMessage
	}
	return nil
}

type RelationInfo struct {
	RelastionType        uint32   `protobuf:"varint,1,opt,name=RelastionType,proto3" json:"RelastionType,omitempty"`
	UllRoleID            uint64   `protobuf:"varint,2,opt,name=UllRoleID,proto3" json:"UllRoleID,omitempty"`
	SzRoleName           string   `protobuf:"bytes,3,opt,name=SzRoleName,proto3" json:"SzRoleName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RelationInfo) Reset()         { *m = RelationInfo{} }
func (m *RelationInfo) String() string { return proto.CompactTextString(m) }
func (*RelationInfo) ProtoMessage()    {}
func (*RelationInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_92f92e011548d12d, []int{12}
}

func (m *RelationInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RelationInfo.Unmarshal(m, b)
}
func (m *RelationInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RelationInfo.Marshal(b, m, deterministic)
}
func (m *RelationInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RelationInfo.Merge(m, src)
}
func (m *RelationInfo) XXX_Size() int {
	return xxx_messageInfo_RelationInfo.Size(m)
}
func (m *RelationInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RelationInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RelationInfo proto.InternalMessageInfo

func (m *RelationInfo) GetRelastionType() uint32 {
	if m != nil {
		return m.RelastionType
	}
	return 0
}

func (m *RelationInfo) GetUllRoleID() uint64 {
	if m != nil {
		return m.UllRoleID
	}
	return 0
}

func (m *RelationInfo) GetSzRoleName() string {
	if m != nil {
		return m.SzRoleName
	}
	return ""
}

//话题
type Topic struct {
	UllTopicID           uint64   `protobuf:"varint,1,opt,name=UllTopicID,proto3" json:"UllTopicID,omitempty"`
	SzTopicTitle         string   `protobuf:"bytes,2,opt,name=SzTopicTitle,proto3" json:"SzTopicTitle,omitempty"`
	SzTopicContent       string   `protobuf:"bytes,3,opt,name=SzTopicContent,proto3" json:"SzTopicContent,omitempty"`
	UllStartTime         int64    `protobuf:"varint,4,opt,name=UllStartTime,proto3" json:"UllStartTime,omitempty"`
	UllEndTime           int64    `protobuf:"varint,5,opt,name=UllEndTime,proto3" json:"UllEndTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Topic) Reset()         { *m = Topic{} }
func (m *Topic) String() string { return proto.CompactTextString(m) }
func (*Topic) ProtoMessage()    {}
func (*Topic) Descriptor() ([]byte, []int) {
	return fileDescriptor_92f92e011548d12d, []int{13}
}

func (m *Topic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Topic.Unmarshal(m, b)
}
func (m *Topic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Topic.Marshal(b, m, deterministic)
}
func (m *Topic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Topic.Merge(m, src)
}
func (m *Topic) XXX_Size() int {
	return xxx_messageInfo_Topic.Size(m)
}
func (m *Topic) XXX_DiscardUnknown() {
	xxx_messageInfo_Topic.DiscardUnknown(m)
}

var xxx_messageInfo_Topic proto.InternalMessageInfo

func (m *Topic) GetUllTopicID() uint64 {
	if m != nil {
		return m.UllTopicID
	}
	return 0
}

func (m *Topic) GetSzTopicTitle() string {
	if m != nil {
		return m.SzTopicTitle
	}
	return ""
}

func (m *Topic) GetSzTopicContent() string {
	if m != nil {
		return m.SzTopicContent
	}
	return ""
}

func (m *Topic) GetUllStartTime() int64 {
	if m != nil {
		return m.UllStartTime
	}
	return 0
}

func (m *Topic) GetUllEndTime() int64 {
	if m != nil {
		return m.UllEndTime
	}
	return 0
}

//排行榜
type RankItem struct {
	UllRoleID            uint64   `protobuf:"varint,1,opt,name=UllRoleID,proto3" json:"UllRoleID,omitempty"`
	UllWorldID           uint64   `protobuf:"varint,2,opt,name=UllWorldID,proto3" json:"UllWorldID,omitempty"`
	SzRoleName           string   `protobuf:"bytes,3,opt,name=SzRoleName,proto3" json:"SzRoleName,omitempty"`
	DwScore              int64    `protobuf:"varint,4,opt,name=DwScore,proto3" json:"DwScore,omitempty"`
	DwRank               int64    `protobuf:"varint,5,opt,name=DwRank,proto3" json:"DwRank,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RankItem) Reset()         { *m = RankItem{} }
func (m *RankItem) String() string { return proto.CompactTextString(m) }
func (*RankItem) ProtoMessage()    {}
func (*RankItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_92f92e011548d12d, []int{14}
}

func (m *RankItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RankItem.Unmarshal(m, b)
}
func (m *RankItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RankItem.Marshal(b, m, deterministic)
}
func (m *RankItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RankItem.Merge(m, src)
}
func (m *RankItem) XXX_Size() int {
	return xxx_messageInfo_RankItem.Size(m)
}
func (m *RankItem) XXX_DiscardUnknown() {
	xxx_messageInfo_RankItem.DiscardUnknown(m)
}

var xxx_messageInfo_RankItem proto.InternalMessageInfo

func (m *RankItem) GetUllRoleID() uint64 {
	if m != nil {
		return m.UllRoleID
	}
	return 0
}

func (m *RankItem) GetUllWorldID() uint64 {
	if m != nil {
		return m.UllWorldID
	}
	return 0
}

func (m *RankItem) GetSzRoleName() string {
	if m != nil {
		return m.SzRoleName
	}
	return ""
}

func (m *RankItem) GetDwScore() int64 {
	if m != nil {
		return m.DwScore
	}
	return 0
}

func (m *RankItem) GetDwRank() int64 {
	if m != nil {
		return m.DwRank
	}
	return 0
}

func init() {
	proto.RegisterEnum("rstudio.gzone_data.GlobalConfigModifyFlag", GlobalConfigModifyFlag_name, GlobalConfigModifyFlag_value)
	proto.RegisterEnum("rstudio.gzone_data.ZoneConfigModifyFlag", ZoneConfigModifyFlag_name, ZoneConfigModifyFlag_value)
	proto.RegisterEnum("rstudio.gzone_data.GameProfileModifyFlag", GameProfileModifyFlag_name, GameProfileModifyFlag_value)
	proto.RegisterEnum("rstudio.gzone_data.ZoneProfileModifyFlag", ZoneProfileModifyFlag_name, ZoneProfileModifyFlag_value)
	proto.RegisterEnum("rstudio.gzone_data.TopicModifyFlag", TopicModifyFlag_name, TopicModifyFlag_value)
	proto.RegisterType((*GlobalZoneConfig)(nil), "rstudio.gzone_data.GlobalZoneConfig")
	proto.RegisterType((*ZoneConfig)(nil), "rstudio.gzone_data.ZoneConfig")
	proto.RegisterType((*GameUserProfile)(nil), "rstudio.gzone_data.GameUserProfile")
	proto.RegisterType((*ZoneUserProfile)(nil), "rstudio.gzone_data.ZoneUserProfile")
	proto.RegisterType((*ZoneProfileSet)(nil), "rstudio.gzone_data.ZoneProfileSet")
	proto.RegisterType((*Moment)(nil), "rstudio.gzone_data.Moment")
	proto.RegisterType((*MediaUnitList)(nil), "rstudio.gzone_data.MediaUnitList")
	proto.RegisterType((*MediaUnitList_MediaUnit)(nil), "rstudio.gzone_data.MediaUnitList.MediaUnit")
	proto.RegisterType((*MomentDataSet)(nil), "rstudio.gzone_data.MomentDataSet")
	proto.RegisterType((*Comment)(nil), "rstudio.gzone_data.Comment")
	proto.RegisterType((*DoLike)(nil), "rstudio.gzone_data.DoLike")
	proto.RegisterType((*Visitor)(nil), "rstudio.gzone_data.Visitor")
	proto.RegisterType((*UndealMsg)(nil), "rstudio.gzone_data.UndealMsg")
	proto.RegisterType((*RelationInfo)(nil), "rstudio.gzone_data.RelationInfo")
	proto.RegisterType((*Topic)(nil), "rstudio.gzone_data.Topic")
	proto.RegisterType((*RankItem)(nil), "rstudio.gzone_data.RankItem")
}

func init() { proto.RegisterFile("gzone_data.proto", fileDescriptor_92f92e011548d12d) }

var fileDescriptor_92f92e011548d12d = []byte{
	// 1328 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x57, 0xcd, 0x6e, 0xdb, 0xc6,
	0x16, 0xbe, 0xfa, 0xb1, 0x2c, 0x1d, 0x49, 0x96, 0x32, 0xf7, 0x26, 0x10, 0x72, 0x2f, 0x02, 0x5f,
	0xb6, 0x08, 0x0c, 0xb7, 0x50, 0x50, 0xb7, 0x28, 0x50, 0x74, 0x25, 0x89, 0x94, 0x43, 0x80, 0x94,
	0x8c, 0x21, 0x95, 0xa0, 0x46, 0x51, 0x81, 0xb1, 0xc6, 0x2a, 0x11, 0x8a, 0x63, 0x48, 0xe3, 0xba,
	0xd1, 0x1b, 0x74, 0xd1, 0x17, 0xe8, 0x23, 0x74, 0xd3, 0x65, 0xd7, 0x7d, 0x80, 0x3e, 0x4c, 0xb7,
	0x5d, 0x15, 0x73, 0x66, 0x28, 0xfe, 0xd8, 0x8e, 0x17, 0xd9, 0xe9, 0x7c, 0xf3, 0xcd, 0xf9, 0x99,
	0xf9, 0xce, 0x19, 0x0a, 0xba, 0xcb, 0x2d, 0x8f, 0xd9, 0x7c, 0x11, 0x88, 0xa0, 0x7f, 0xb5, 0xe6,
	0x82, 0x13, 0xb2, 0xde, 0x88, 0xeb, 0x45, 0xc8, 0xfb, 0xe9, 0x8a, 0xf1, 0x2d, 0x74, 0x4f, 0x23,
	0xfe, 0x26, 0x88, 0xce, 0x79, 0xcc, 0x46, 0x3c, 0xbe, 0x0c, 0x97, 0xc4, 0x80, 0xd6, 0xd0, 0xe5,
	0x2b, 0x16, 0x0b, 0x27, 0x5c, 0x85, 0xa2, 0x57, 0x3a, 0x2c, 0x1d, 0xed, 0xd1, 0x1c, 0x46, 0x3e,
	0x86, 0xf6, 0x70, 0xc4, 0x57, 0x29, 0xa9, 0x8c, 0xa4, 0x3c, 0x68, 0xfc, 0x08, 0x90, 0xf1, 0xfb,
	0x1c, 0x0e, 0xcc, 0x9b, 0xdc, 0x26, 0xe9, 0xb9, 0x4d, 0x0b, 0xa8, 0xe2, 0xb9, 0x6c, 0xb3, 0x09,
	0x96, 0x2c, 0x75, 0x8e, 0xbc, 0x2c, 0x4a, 0x9e, 0x42, 0xdd, 0xbc, 0xa1, 0x6c, 0x15, 0xc6, 0x8b,
	0x5e, 0x05, 0x19, 0x3b, 0xdb, 0xf8, 0xad, 0x04, 0x9d, 0xd3, 0x60, 0xc5, 0x66, 0x1b, 0xb6, 0x3e,
	0x5b, 0xf3, 0xcb, 0x30, 0x62, 0x92, 0xef, 0x6d, 0xa7, 0x57, 0x2c, 0xb6, 0x4d, 0x8c, 0xdc, 0xa0,
	0x3b, 0x9b, 0x3c, 0x03, 0xf0, 0xb6, 0x94, 0x47, 0x6c, 0x12, 0xac, 0x18, 0xc6, 0x6b, 0xd0, 0x0c,
	0x42, 0xfe, 0x07, 0x0d, 0xf3, 0xe6, 0x35, 0x5f, 0x47, 0x0b, 0xdb, 0xd4, 0xc1, 0x52, 0x80, 0xf4,
	0x60, 0xdf, 0xbc, 0x71, 0xd8, 0x0f, 0x2c, 0xea, 0x55, 0x71, 0x2d, 0x31, 0xc9, 0x11, 0x74, 0x64,
	0x0a, 0x32, 0x15, 0x9d, 0x46, 0x6f, 0x0f, 0x9d, 0x17, 0x61, 0xe3, 0x1a, 0x3a, 0xf2, 0xac, 0xb2,
	0x09, 0x1f, 0x42, 0xd3, 0xdb, 0xbe, 0x64, 0xc1, 0x62, 0xbc, 0x96, 0x59, 0xa9, 0x9c, 0xb3, 0x90,
	0x62, 0x78, 0xe1, 0x32, 0x0e, 0xc4, 0xf5, 0x3a, 0xc9, 0x3b, 0x0b, 0xa9, 0xc2, 0x1c, 0x7e, 0x11,
	0x88, 0x90, 0xc7, 0x98, 0x39, 0x16, 0x96, 0x20, 0xc6, 0xdf, 0x65, 0x38, 0x90, 0x71, 0x75, 0x4c,
	0x8f, 0x09, 0x59, 0xeb, 0x2c, 0x8a, 0x64, 0xe9, 0xfa, 0xa0, 0xaa, 0x34, 0x05, 0x88, 0x0d, 0x6d,
	0x4f, 0x64, 0x76, 0x60, 0xd0, 0xe6, 0xc9, 0x47, 0xfd, 0xdb, 0xea, 0xea, 0x17, 0x0a, 0xa2, 0xf9,
	0x9d, 0xca, 0x95, 0x3e, 0x83, 0xb1, 0x74, 0x55, 0xb9, 0xdf, 0x55, 0xe1, 0x32, 0x69, 0x7e, 0x27,
	0x19, 0x42, 0x4b, 0xf9, 0x56, 0x5a, 0xc3, 0x6b, 0x68, 0x9e, 0x3c, 0xbb, 0x2f, 0x29, 0xc5, 0xa2,
	0xb9, 0x3d, 0x4a, 0x77, 0xaf, 0xc2, 0x4d, 0x28, 0xf8, 0x7a, 0xc4, 0xaf, 0x63, 0x81, 0x57, 0x85,
	0xba, 0xcb, 0xa2, 0x39, 0x1d, 0x2b, 0x5e, 0xad, 0xa0, 0x63, 0xc5, 0x3b, 0x84, 0xa6, 0x79, 0xe3,
	0x84, 0x6f, 0x99, 0x22, 0xed, 0x23, 0x29, 0x0b, 0x19, 0x7f, 0x95, 0xa1, 0xa6, 0xba, 0x4a, 0x92,
	0x67, 0x51, 0xa4, 0x8c, 0xdd, 0xb1, 0x67, 0xa1, 0xfc, 0xb5, 0x94, 0x8b, 0xd7, 0x92, 0x17, 0x70,
	0xe5, 0x96, 0x80, 0x9f, 0x01, 0xcc, 0xa2, 0x28, 0x51, 0x70, 0x15, 0xb7, 0x67, 0x10, 0xbd, 0xee,
	0xf3, 0xab, 0xf0, 0xc2, 0x36, 0xb1, 0x70, 0xb5, 0xae, 0x11, 0xf2, 0x04, 0x6a, 0x43, 0x7b, 0xf3,
	0x92, 0x27, 0xc5, 0x6a, 0x4b, 0xe2, 0xe6, 0x8d, 0x1f, 0xae, 0x18, 0xd6, 0x57, 0xa1, 0xda, 0x92,
	0xd9, 0x7a, 0xdb, 0x11, 0x8f, 0x05, 0x8b, 0x45, 0xaf, 0x8e, 0xe9, 0xa4, 0x40, 0x41, 0x95, 0x8d,
	0xa2, 0x2a, 0x09, 0x81, 0xea, 0x70, 0x72, 0xbd, 0xea, 0x01, 0xc6, 0xc2, 0xdf, 0xc4, 0x82, 0xd6,
	0x60, 0x23, 0x5c, 0xb6, 0x08, 0x03, 0x33, 0x10, 0x41, 0xaf, 0x89, 0x57, 0xfc, 0xff, 0xbb, 0xae,
	0x18, 0x49, 0xb3, 0x38, 0x14, 0x4e, 0xb8, 0x11, 0x34, 0xb7, 0xcd, 0xf8, 0xa3, 0x04, 0xed, 0xdc,
	0x3a, 0x99, 0xa6, 0x8e, 0xa5, 0xdd, 0x2b, 0x1d, 0x56, 0x8e, 0x9a, 0x27, 0x9f, 0x3c, 0xe8, 0x38,
	0xb5, 0x68, 0xce, 0xc1, 0xd3, 0x39, 0x34, 0x76, 0x4b, 0x72, 0xea, 0x0c, 0x57, 0x6a, 0x6c, 0xe9,
	0x79, 0xb7, 0xb3, 0xd5, 0x44, 0x3a, 0x0b, 0xd6, 0xc1, 0xea, 0x33, 0xdd, 0xbb, 0x3b, 0x3b, 0xb3,
	0x76, 0xa2, 0xaf, 0x73, 0x67, 0x1b, 0xbf, 0x96, 0xa1, 0xad, 0x74, 0x21, 0x4b, 0x92, 0x3d, 0xfb,
	0x25, 0xd4, 0x3d, 0xa1, 0x20, 0x8c, 0xd2, 0x3c, 0x79, 0x7a, 0x67, 0xfe, 0xc8, 0xa0, 0x3b, 0xae,
	0xd2, 0xb2, 0xcf, 0x45, 0x10, 0x49, 0x55, 0xca, 0x23, 0xdf, 0xcd, 0xda, 0x2c, 0x4a, 0xbe, 0x80,
	0xfd, 0xc1, 0x46, 0x48, 0xab, 0x57, 0xc1, 0xe3, 0xb9, 0xd3, 0xbd, 0xc9, 0x25, 0x83, 0x26, 0x54,
	0xf2, 0x29, 0x3c, 0xd2, 0x7e, 0x74, 0x63, 0xc8, 0x00, 0x6a, 0x42, 0xde, 0x5e, 0x20, 0x5f, 0x03,
	0x0c, 0x36, 0x42, 0x03, 0xbd, 0x3d, 0x0c, 0xf3, 0xdf, 0xbb, 0xc2, 0x68, 0x0a, 0xcd, 0xd0, 0xe5,
	0x08, 0x1e, 0xda, 0x1b, 0x4c, 0x50, 0x0a, 0xb4, 0x4e, 0x13, 0xd3, 0xf8, 0xb9, 0x0c, 0xfb, 0x09,
	0xeb, 0xfd, 0xa3, 0xed, 0xa1, 0x47, 0xc0, 0x80, 0xd6, 0x2c, 0x4a, 0x32, 0xd6, 0xef, 0x40, 0x95,
	0xe6, 0xb0, 0x62, 0x1f, 0x57, 0x6f, 0xf7, 0x71, 0xda, 0x31, 0x7b, 0xf7, 0x77, 0x4c, 0xad, 0xd8,
	0x31, 0xcf, 0xe1, 0x40, 0x26, 0xca, 0xae, 0xa2, 0x77, 0x98, 0xed, 0x02, 0xfb, 0xad, 0x4a, 0x0b,
	0xa8, 0x7a, 0x11, 0x10, 0xc0, 0x22, 0xea, 0xc9, 0x8b, 0xb0, 0x83, 0x8c, 0xef, 0xa0, 0xa6, 0xee,
	0xe9, 0x03, 0x4f, 0x23, 0xad, 0xa3, 0x92, 0xad, 0xc3, 0x78, 0x0b, 0xfb, 0x7a, 0x5c, 0xea, 0x03,
	0xd3, 0xd6, 0x2e, 0x46, 0x0e, 0x93, 0x5f, 0x12, 0xde, 0x56, 0x9b, 0x99, 0x48, 0x79, 0xf0, 0xde,
	0x60, 0x7f, 0x96, 0xa0, 0x31, 0x8b, 0x17, 0x2c, 0x88, 0xdc, 0xcd, 0x52, 0xb3, 0xde, 0x5d, 0x25,
	0x9d, 0xa6, 0x2d, 0x72, 0x02, 0x35, 0x4f, 0x89, 0xb7, 0x7c, 0x7f, 0x6f, 0x68, 0xf1, 0x6a, 0x26,
	0xf9, 0x0a, 0x1a, 0xde, 0x4e, 0x8c, 0xea, 0x61, 0x7a, 0xaf, 0x18, 0x53, 0xb6, 0xda, 0xaa, 0x3f,
	0x55, 0xf4, 0x4b, 0xf4, 0xd0, 0x56, 0xcd, 0x36, 0xd6, 0xd0, 0xa2, 0x2c, 0xc2, 0x21, 0x68, 0xc7,
	0x97, 0x5c, 0x9e, 0x8e, 0xb4, 0x37, 0x12, 0xc8, 0x14, 0x96, 0x07, 0x3f, 0xec, 0x69, 0x30, 0x7e,
	0x2f, 0xc1, 0x1e, 0x8e, 0xf9, 0xc2, 0x23, 0x50, 0xba, 0xf5, 0x08, 0x18, 0xd0, 0xf2, 0xb6, 0x68,
	0xf8, 0xa1, 0x88, 0x92, 0xab, 0xca, 0x61, 0x52, 0xa8, 0xda, 0x4e, 0xb4, 0xac, 0x22, 0x16, 0x50,
	0xad, 0x0d, 0x4f, 0x04, 0x6b, 0x81, 0xf7, 0x5a, 0xc5, 0x7b, 0xcd, 0x61, 0x3a, 0x1f, 0x2b, 0x5e,
	0x64, 0xda, 0x25, 0x83, 0x18, 0xbf, 0x94, 0xa0, 0x4e, 0x83, 0xf8, 0xad, 0x2d, 0xd8, 0xea, 0x61,
	0x35, 0x67, 0xde, 0xbf, 0xf2, 0x5d, 0xef, 0xdf, 0x7b, 0xdf, 0x4f, 0xfc, 0xc4, 0xf3, 0x2e, 0xf8,
	0x3a, 0xc9, 0x34, 0x31, 0x95, 0xe8, 0x64, 0x16, 0x69, 0x3f, 0x4b, 0xeb, 0xf8, 0x1b, 0x78, 0xa2,
	0x3e, 0xad, 0xd5, 0xe7, 0x85, 0xcb, 0x17, 0xe1, 0xe5, 0xbb, 0x71, 0x14, 0x2c, 0x49, 0x17, 0x5a,
	0xa7, 0x23, 0x77, 0x3c, 0x37, 0xad, 0xf1, 0x60, 0xe6, 0xf8, 0xdd, 0x7f, 0x91, 0x27, 0x40, 0x10,
	0x19, 0x4d, 0x5d, 0xd7, 0x9a, 0xf8, 0x73, 0xc7, 0x76, 0x6d, 0xbf, 0x5b, 0x22, 0x8f, 0xe1, 0x11,
	0xe2, 0xee, 0xd4, 0xb5, 0xdc, 0x04, 0x2e, 0x1f, 0x87, 0xf0, 0x9f, 0xf4, 0xbb, 0x25, 0xef, 0xf8,
	0xfc, 0x96, 0xe3, 0xf3, 0xbb, 0x1c, 0x27, 0xb8, 0x6b, 0x79, 0xde, 0xe0, 0xd4, 0x4a, 0x3c, 0x93,
	0x0e, 0x34, 0x11, 0xa7, 0x96, 0x6b, 0x4f, 0xcc, 0x6e, 0xf5, 0xf8, 0xa7, 0x12, 0x3c, 0xce, 0x7c,
	0xa6, 0x16, 0xaa, 0x38, 0xcb, 0x05, 0x4b, 0x90, 0xe9, 0x99, 0x35, 0x99, 0xdb, 0x66, 0xb7, 0x44,
	0x08, 0x1c, 0x20, 0x42, 0xa7, 0x8e, 0x35, 0x9f, 0x0c, 0x5c, 0xab, 0x5b, 0x26, 0x8f, 0xa0, 0x8d,
	0xd8, 0xeb, 0x29, 0x75, 0x4c, 0x49, 0xab, 0x92, 0x03, 0x00, 0x84, 0x1c, 0xeb, 0x95, 0xe5, 0x74,
	0xeb, 0x58, 0xb6, 0xb4, 0x4f, 0x07, 0xae, 0x35, 0x3f, 0xa3, 0xd3, 0xb1, 0xed, 0x58, 0xdd, 0xee,
	0x31, 0x83, 0xc7, 0x99, 0xcf, 0xc7, 0x42, 0xdd, 0x2a, 0x95, 0xc1, 0x58, 0xa5, 0xf2, 0x6f, 0xe8,
	0x20, 0xf2, 0xd2, 0x1a, 0x98, 0xf3, 0x31, 0x95, 0x91, 0x31, 0x1b, 0x04, 0x3d, 0xfb, 0x74, 0x32,
	0xf0, 0x67, 0x54, 0x67, 0x83, 0x98, 0x33, 0x1d, 0x0d, 0x7c, 0x7b, 0x3a, 0xe9, 0x56, 0x8f, 0xbf,
	0x87, 0x0e, 0x2a, 0x35, 0x13, 0xa0, 0x03, 0x4d, 0x3f, 0x57, 0x6a, 0x1b, 0x1a, 0x12, 0xf0, 0x6d,
	0xdf, 0x91, 0x9e, 0xf5, 0xfa, 0x68, 0x3a, 0xf1, 0xad, 0x89, 0x3c, 0x47, 0x02, 0x07, 0x12, 0xf0,
	0xfc, 0x01, 0xf5, 0xe7, 0xbe, 0xed, 0x5a, 0xdd, 0xaa, 0xcc, 0x52, 0x62, 0xd6, 0xc4, 0x54, 0x48,
	0x7d, 0x78, 0x74, 0xfe, 0x7c, 0x19, 0x8a, 0xfe, 0x05, 0x5f, 0xb0, 0x3e, 0x0f, 0xfa, 0x17, 0x7c,
	0xf5, 0x42, 0x8f, 0x89, 0x17, 0x38, 0x26, 0x5e, 0xe0, 0x1f, 0xb7, 0x0b, 0x1e, 0xbd, 0xa9, 0xe1,
	0xaf, 0xcf, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0x10, 0x9c, 0xe2, 0xf3, 0xd6, 0x0d, 0x00, 0x00,
}
